-- Generated from src/lib/store/seedQuestions.ts — run `npm run gen:seed-sql`
-- to regenerate after editing the question list. Run after schema.sql.
insert into questions (id, text, category, option_a, option_b, emoji_a, emoji_b, seeded_result_percentage_a, minimum_votes, status) values
  ('sweet-or-savory-breakfast', 'Which would most people choose for breakfast?', 'Food', 'Sweet', 'Savory', '🍩', '🥓', 47, 5, 'published'),
  ('pizza-or-burger-movie-night', 'Which would most people choose for a movie night?', 'Food', 'Pizza', 'Burger', '🍕', '🍔', 62, 5, 'published'),
  ('pineapple-on-pizza', 'Pineapple on pizza — yes or no?', 'Food', 'Yes', 'No', '🍍', '🚫', 33, 5, 'published'),
  ('cereal-or-milk-first', 'Which goes into the bowl first?', 'Food', 'Cereal', 'Milk', '🥣', '🥛', 71, 5, 'published'),
  ('rewatch-or-new-movie', 'Which would most people choose tonight?', 'Movies', 'Rewatch a favorite', 'Try something new', '🔁', '🎬', 58, 5, 'published'),
  ('sweet-or-salty-popcorn', 'Which popcorn wins at the cinema?', 'Movies', 'Sweet', 'Salty', '🍿', '🧂', 41, 5, 'published'),
  ('subtitles-on-or-off', 'Subtitles on, even in your own language?', 'Movies', 'On', 'Off', '📝', '🙈', 45, 5, 'published'),
  ('cinema-or-couch', 'Which would most people choose to watch a new release?', 'Movies', 'Cinema', 'Couch at home', '🎥', '🛋️', 39, 5, 'published'),
  ('play-or-watch-sport', 'Which would most people choose?', 'Sport', 'Play the sport', 'Watch the sport', '⚽', '📺', 54, 5, 'published'),
  ('morning-or-evening-workout', 'When do most people prefer to work out?', 'Sport', 'Morning', 'Evening', '🌅', '🌙', 48, 5, 'published'),
  ('team-or-solo-sport', 'Which would most people choose to play?', 'Sport', 'Team sport', 'Solo sport', '🤝', '🏃', 61, 5, 'published'),
  ('win-ugly-or-lose-beautifully', 'Which would most people rather do?', 'Sport', 'Win ugly', 'Lose playing beautifully', '🏆', '🎨', 67, 5, 'published'),
  ('iphone-or-android', 'Which would most people choose?', 'Technology', 'iPhone', 'Android', '📱', '🤖', 55, 5, 'published'),
  ('instructions-or-figure-it-out', 'New gadget just arrived. What now?', 'Technology', 'Figure it out yourself', 'Read the instructions', '🧩', '📖', 73, 5, 'published'),
  ('keyboard-or-phone-typing', 'Which would most people choose to type a long message?', 'Technology', 'Real keyboard', 'Phone', '⌨️', '📱', 64, 5, 'published'),
  ('keep-phone-or-upgrade-yearly', 'Which would most people choose?', 'Technology', 'Keep it till it breaks', 'New phone every year', '🔧', '🆕', 78, 5, 'published'),
  ('study-night-before-or-spread-out', 'How does most people study for a big test?', 'School', 'Night before', 'Spread it out', '🌙', '📅', 52, 5, 'published'),
  ('solo-or-group-project', 'Given the choice, which would most people pick?', 'School', 'Solo project', 'Group project', '🙋', '👥', 60, 5, 'published'),
  ('front-row-or-back-row', 'Which seat do most people choose in class?', 'School', 'Back row', 'Front row', '😎', '🙋‍♂️', 69, 5, 'published'),
  ('summer-or-winter-break', 'Which break do most people look forward to more?', 'School', 'Summer break', 'Winter break', '🌞', '❄️', 74, 5, 'published'),
  ('morning-or-evening-shower', 'Which would most people choose?', 'Everyday Life', 'Morning shower', 'Evening shower', '🚿', '🌙', 56, 5, 'published'),
  ('window-or-aisle-seat', 'On a long trip, which seat do most people pick?', 'Everyday Life', 'Window', 'Aisle', '🪟', '🚶', 63, 5, 'published'),
  ('text-or-call', 'Which would most people choose to reach a friend?', 'Everyday Life', 'Text', 'Call', '💬', '📞', 81, 5, 'published'),
  ('early-bird-or-night-owl', 'Which are most people?', 'Everyday Life', 'Night owl', 'Early bird', '🦉', '🐦', 57, 5, 'published'),
  ('cats-or-dogs', 'Which would most people choose?', 'Random', 'Dogs', 'Cats', '🐶', '🐱', 59, 5, 'published'),
  ('beach-or-mountain-vacation', 'Which vacation would most people choose?', 'Random', 'Beach', 'Mountains', '🏖️', '⛰️', 55, 5, 'published'),
  ('more-time-or-more-money', 'Which would most people choose, if they had to pick?', 'Random', 'More time', 'More money', '⏳', '💰', 66, 5, 'published'),
  ('lots-of-emojis-or-none', 'Which describes how most people text?', 'Internet Culture', 'Lots of emojis', 'No emojis at all', '😂', '🔠', 53, 5, 'published'),
  ('read-or-skip-comments', 'Which would most people choose on a video?', 'Internet Culture', 'Skip the comments', 'Read the comments', '🙈', '💬', 62, 5, 'published'),
  ('post-the-moment-or-watch', 'At a big moment, what do most people do first?', 'Internet Culture', 'Just watch it happen', 'Post it', '👀', '📸', 71, 5, 'published')
on conflict (id) do nothing;
