-- Generated from src/lib/store/seedQuestions.ts — run `npm run gen:seed-sql`
-- to regenerate after editing the question list. Run after schema.sql and functions.sql.
insert into questions (id, text, category, option_a, option_b, emoji_a, emoji_b, seeded_result_percentage_a, minimum_votes, status) values
  ('sweet-or-savory-breakfast', 'What does the crowd actually reach for at breakfast?', 'Food', 'Sweet', 'Savory', '🍩', '🥓', 47, 5, 'published'),
  ('pizza-or-burger-movie-night', 'Movie night''s on — what gets ordered?', 'Food', 'Pizza', 'Burger', '🍕', '🍔', 62, 5, 'published'),
  ('pineapple-on-pizza', 'Pineapple on pizza — yes or no?', 'Food', 'Yes', 'No', '🍍', '🚫', 33, 5, 'published'),
  ('cereal-or-milk-first', 'Which goes into the bowl first?', 'Food', 'Cereal', 'Milk', '🥣', '🥛', 71, 5, 'published'),
  ('rewatch-or-new-movie', 'Remote in hand — does the crowd rewatch a favorite or try something new?', 'Movies', 'Rewatch a favorite', 'Try something new', '🔁', '🎬', 58, 5, 'published'),
  ('sweet-or-salty-popcorn', 'Which popcorn wins at the cinema?', 'Movies', 'Sweet', 'Salty', '🍿', '🧂', 41, 5, 'published'),
  ('subtitles-on-or-off', 'Subtitles on, even in your own language?', 'Movies', 'On', 'Off', '📝', '🙈', 45, 5, 'published'),
  ('cinema-or-couch', 'A new release just dropped — where does the crowd watch it?', 'Movies', 'Cinema', 'Couch at home', '🎥', '🛋️', 39, 5, 'published'),
  ('play-or-watch-sport', 'Given the choice, does the crowd play or watch?', 'Sport', 'Play the sport', 'Watch the sport', '⚽', '📺', 54, 5, 'published'),
  ('morning-or-evening-workout', 'When do most people prefer to work out?', 'Sport', 'Morning', 'Evening', '🌅', '🌙', 48, 5, 'published'),
  ('team-or-solo-sport', 'Picking a sport, does the crowd go team or solo?', 'Sport', 'Team sport', 'Solo sport', '🤝', '🏃', 61, 5, 'published'),
  ('win-ugly-or-lose-beautifully', 'Deep down, which does the crowd actually prefer?', 'Sport', 'Win ugly', 'Lose playing beautifully', '🏆', '🎨', 67, 5, 'published'),
  ('iphone-or-android', 'Check your pocket — which does the crowd actually carry?', 'Technology', 'iPhone', 'Android', '📱', '🤖', 55, 5, 'published'),
  ('instructions-or-figure-it-out', 'New gadget just arrived. What now?', 'Technology', 'Figure it out yourself', 'Read the instructions', '🧩', '📖', 73, 5, 'published'),
  ('keyboard-or-phone-typing', 'Writing a long message, what does the crowd reach for?', 'Technology', 'Real keyboard', 'Phone', '⌨️', '📱', 64, 5, 'published'),
  ('keep-phone-or-upgrade-yearly', 'How does the crowd actually treat their phone?', 'Technology', 'Keep it till it breaks', 'New phone every year', '🔧', '🆕', 78, 5, 'published'),
  ('study-night-before-or-spread-out', 'How does the crowd really study for a big test?', 'School', 'Night before', 'Spread it out', '🌙', '📅', 52, 5, 'published'),
  ('solo-or-group-project', 'Given the choice, does the crowd go solo or team up?', 'School', 'Solo project', 'Group project', '🙋', '👥', 60, 5, 'published'),
  ('front-row-or-back-row', 'Which seat do most people choose in class?', 'School', 'Back row', 'Front row', '😎', '🙋‍♂️', 69, 5, 'published'),
  ('summer-or-winter-break', 'Which break do most people look forward to more?', 'School', 'Summer break', 'Winter break', '🌞', '❄️', 74, 5, 'published'),
  ('morning-or-evening-shower', 'Does the crowd shower to start the day, or end it?', 'Everyday Life', 'Morning shower', 'Evening shower', '🚿', '🌙', 56, 5, 'published'),
  ('window-or-aisle-seat', 'On a long trip, which seat do most people pick?', 'Everyday Life', 'Window', 'Aisle', '🪟', '🚶', 63, 5, 'published'),
  ('text-or-call', 'To reach a friend, what does the crowd actually do?', 'Everyday Life', 'Text', 'Call', '💬', '📞', 81, 5, 'published'),
  ('early-bird-or-night-owl', 'Which is the crowd, deep down?', 'Everyday Life', 'Night owl', 'Early bird', '🦉', '🐦', 57, 5, 'published'),
  ('cats-or-dogs', 'Team dog or team cat — where does the crowd land?', 'Random', 'Dogs', 'Cats', '🐶', '🐱', 59, 5, 'published'),
  ('beach-or-mountain-vacation', 'Picking a vacation, where does the crowd go?', 'Random', 'Beach', 'Mountains', '🏖️', '⛰️', 55, 5, 'published'),
  ('more-time-or-more-money', 'Forced to pick just one, what does the crowd choose?', 'Random', 'More time', 'More money', '⏳', '💰', 66, 5, 'published'),
  ('lots-of-emojis-or-none', 'How does the crowd actually text?', 'Internet Culture', 'Lots of emojis', 'No emojis at all', '😂', '🔠', 53, 5, 'published'),
  ('read-or-skip-comments', 'On a video, does the crowd read the comments or skip them?', 'Internet Culture', 'Skip the comments', 'Read the comments', '🙈', '💬', 62, 5, 'published'),
  ('post-the-moment-or-watch', 'At a big moment, what do most people do first?', 'Internet Culture', 'Just watch it happen', 'Post it', '👀', '📸', 71, 5, 'published'),
  ('ketchup-or-mayo-fries', 'What''s the crowd actually dipping their fries in?', 'Food', 'Ketchup', 'Mayo', '🍅', '🥫', 66, 5, 'published'),
  ('thin-or-deep-dish-pizza', 'Ordering pizza — thin crust or deep dish?', 'Food', 'Thin crust', 'Deep dish', '🍕', '🥧', 58, 5, 'published'),
  ('cone-or-cup-ice-cream', 'Ice cream truck''s here — cone or cup?', 'Food', 'Cone', 'Cup', '🍦', '🍨', 61, 5, 'published'),
  ('coffee-or-tea-to-start-day', 'What actually gets the day going?', 'Food', 'Coffee', 'Tea', '☕', '🍵', 74, 5, 'published'),
  ('spicy-or-mild-by-default', 'Ordering something new, does the crowd go spicy or play it safe?', 'Food', 'Spicy', 'Mild', '🌶️', '🧊', 45, 5, 'published'),
  ('same-order-or-try-something-new', 'At a favorite restaurant, does the crowd order the usual or try something new?', 'Food', 'The usual', 'Something new', '🔁', '🆕', 63, 5, 'published'),
  ('fries-or-onion-rings', 'Picking a side, what wins?', 'Food', 'Fries', 'Onion rings', '🍟', '🧅', 77, 5, 'published'),
  ('chocolate-or-vanilla-default', 'No other flavor available — which does the crowd actually prefer?', 'Food', 'Chocolate', 'Vanilla', '🍫', '🍦', 60, 5, 'published'),
  ('cook-or-takeout-tired-night', 'End of a long day — cook or order in?', 'Food', 'Cook at home', 'Order in', '🍳', '🥡', 40, 5, 'published'),
  ('crunchy-or-creamy-peanut-butter', 'Opening the jar — which texture wins?', 'Food', 'Crunchy', 'Creamy', '🥜', '🧈', 47, 5, 'published'),
  ('salt-on-watermelon', 'Salt on watermelon — yes or no?', 'Food', 'Yes', 'No', '🧂', '🚫', 24, 5, 'published'),
  ('hot-sauce-on-everything', 'Does the crowd reach for hot sauce on most meals, or just sometimes?', 'Food', 'On almost everything', 'Only sometimes', '🔥', '🤏', 37, 5, 'published'),
  ('sushi-roll-or-sashimi', 'At a sushi spot, what does the crowd actually order more of?', 'Food', 'Rolls', 'Sashimi', '🍣', '🐟', 71, 5, 'published'),
  ('butter-or-oil-for-bread', 'Bread basket arrives — butter or olive oil?', 'Food', 'Butter', 'Olive oil', '🧈', '🫒', 54, 5, 'published'),
  ('split-bill-evenly-or-by-order', 'Splitting a group bill — evenly, or by what each person ordered?', 'Food', 'Split evenly', 'By what you ordered', '➗', '🧾', 42, 5, 'published'),
  ('shopping-list-or-wander-aisles', 'At the grocery store, does the crowd stick to a list or wing it?', 'Food', 'Stick to the list', 'Wing it', '📝', '🛒', 55, 5, 'published'),
  ('meal-prep-or-decide-daily', 'Planning meals for the week — prep ahead, or decide each day?', 'Food', 'Prep ahead', 'Decide day by day', '📦', '🤷', 34, 5, 'published'),
  ('burnt-or-lightly-toasted-marshmallow', 'Around the fire, how does the crowd like their marshmallow?', 'Food', 'Burnt', 'Lightly toasted', '🔥', '🤎', 46, 5, 'published'),
  ('cake-or-pie-birthday', 'Birthday''s here — cake or pie?', 'Food', 'Cake', 'Pie', '🎂', '🥧', 83, 5, 'published'),
  ('froyo-or-ice-cream', 'Dessert run — froyo or ice cream?', 'Food', 'Frozen yogurt', 'Ice cream', '🍦', '🍨', 30, 5, 'published'),
  ('skip-dessert-or-always-order-it', 'At a restaurant, does the crowd order dessert or skip it?', 'Food', 'Always order it', 'Usually skip it', '🍮', '🙅', 41, 5, 'published'),
  ('drive-thru-or-walk-in', 'Grabbing fast food — drive-thru or walk in?', 'Food', 'Drive-thru', 'Walk in', '🚗', '🚶', 69, 5, 'published'),
  ('burger-with-hands-or-utensils', 'Eating a burger — hands or fork and knife?', 'Food', 'Hands', 'Fork and knife', '✋', '🍴', 88, 5, 'published'),
  ('free-samples-or-skip-them', 'Free samples at the store — try them or walk past?', 'Food', 'Try them', 'Walk past', '🍢', '🚶‍♂️', 57, 5, 'published'),
  ('same-coffee-order-or-mix-it-up', 'Ordering coffee, does the crowd stick to the usual or mix it up?', 'Food', 'Same order every time', 'Mix it up', '☕', '🔀', 62, 5, 'published'),
  ('plain-or-flavored-yogurt', 'Grabbing yogurt — plain or flavored?', 'Food', 'Plain', 'Flavored', '⚪', '🍓', 27, 5, 'published'),
  ('big-breakfast-or-skip-it', 'Mornings — big breakfast or skip it entirely?', 'Food', 'Big breakfast', 'Skip it', '🍳', '⏭️', 48, 5, 'published'),
  ('refill-drink-before-leaving', 'Free refills at a fast food spot — top up before leaving, or not bother?', 'Food', 'Top it up', 'Not bother', '🥤', '🚶', 44, 5, 'published'),
  ('homemade-or-store-bought-cake', 'Birthday cake — homemade or store-bought?', 'Food', 'Homemade', 'Store-bought', '🧁', '🛒', 39, 5, 'published'),
  ('still-or-sparkling-water-default', 'Ordering water at a restaurant, what''s the default?', 'Food', 'Still', 'Sparkling', '💧', '🫧', 76, 5, 'published'),
  ('one-napkin-or-grab-a-stack', 'Grabbing napkins with takeout — just one, or a stack?', 'Food', 'Just one', 'Grab a stack', '🧻', '🤲', 35, 5, 'published'),
  ('snack-all-day-or-three-meals', 'How does the crowd actually eat through the day?', 'Food', 'Snack throughout', 'Three set meals', '🍿', '🍽️', 43, 5, 'published'),
  ('new-restaurant-or-go-to-favorite', 'Date night — try a new restaurant or go to a reliable favorite?', 'Food', 'Try somewhere new', 'Go to the favorite', '🆕', '❤️', 41, 5, 'published'),
  ('bagel-toasted-or-not', 'Bagel from the shop — toasted or not?', 'Food', 'Toasted', 'Not toasted', '🔥', '🥯', 79, 5, 'published'),
  ('order-off-menu-or-stick-to-menu', 'At a restaurant, does the crowd ever order off-menu, or always stick to what''s listed?', 'Food', 'Order off-menu sometimes', 'Always stick to the menu', '🗣️', '📋', 33, 5, 'published'),
  ('eat-vegetables-first-or-last-on-plate', 'Clearing a plate — vegetables first, or saved for last?', 'Food', 'Vegetables first', 'Saved for last', '🥦', '⏳', 52, 5, 'published'),
  ('bring-lunch-or-buy-lunch-at-work', 'Workday lunch — packed from home, or bought?', 'Food', 'Packed from home', 'Bought', '🥪', '💳', 45, 5, 'published'),
  ('guac-extra-charge-or-skip-it', 'Extra charge for guac — pay it, or skip it?', 'Food', 'Pay it', 'Skip it', '🥑', '🙅', 58, 5, 'published'),
  ('one-big-meal-or-many-small-ones', 'Given the choice, does the crowd prefer one big meal a day or several small ones?', 'Food', 'One big meal', 'Several small ones', '🍛', '🍱', 31, 5, 'published'),
  ('leftovers-cold-or-reheated', 'Cold pizza the next morning — eaten cold, or reheated first?', 'Food', 'Eaten cold', 'Reheated first', '🥶', '🔥', 35, 5, 'published'),
  ('sneak-snacks-into-theater', 'Sneaking snacks into the movie theater — does the crowd do it?', 'Movies', 'Sneak them in', 'Buy at the theater', '😈', '🎟️', 61, 5, 'published'),
  ('talk-during-movie-or-silent', 'In the theater, does the crowd stay silent or whisper commentary?', 'Movies', 'Stay silent', 'Whisper commentary', '🤫', '💬', 72, 5, 'published'),
  ('spoilers-avoid-or-dont-care', 'Before watching something, does the crowd avoid spoilers or not really care?', 'Movies', 'Avoid them', 'Don''t really care', '🙈', '🤷', 68, 5, 'published'),
  ('movie-in-theaters-or-streaming', 'New movie''s out — see it in theaters, or wait for streaming?', 'Movies', 'In theaters', 'Wait for streaming', '🎬', '📺', 38, 5, 'published'),
  ('book-or-movie-first', 'A story exists as both — does the crowd read the book or watch the movie first?', 'Movies', 'Read the book', 'Watch the movie', '📖', '🎬', 46, 5, 'published'),
  ('credits-stay-or-leave', 'Credits start rolling — stay seated or head out?', 'Movies', 'Stay seated', 'Head out', '🎬', '🚶', 33, 5, 'published'),
  ('horror-alone-or-with-others', 'Watching a horror movie — alone, or with people?', 'Movies', 'Alone', 'With others', '🕯️', '👥', 22, 5, 'published'),
  ('happy-or-sad-ending', 'Given the choice, which ending does the crowd actually prefer?', 'Movies', 'Happy ending', 'Sad ending', '😊', '😢', 74, 5, 'published'),
  ('animated-or-live-action', 'Picking a movie night pick, animated or live action?', 'Movies', 'Animated', 'Live action', '🎨', '🎥', 44, 5, 'published'),
  ('binge-a-season-or-spread-out', 'A new season just dropped — binge it or spread it out?', 'Movies', 'Binge it', 'Spread it out', '🍿', '📅', 57, 5, 'published'),
  ('trailer-watch-or-skip', 'Before a movie, does the crowd watch trailers or skip straight to the film?', 'Movies', 'Watch the trailers', 'Skip to the film', '📽️', '⏭️', 65, 5, 'published'),
  ('theater-recliner-or-standard-seat', 'At the movies, does the crowd spring for the recliner seats or stick with standard?', 'Movies', 'Recliner seats', 'Standard seats', '🛋️', '💺', 55, 5, 'published'),
  ('rate-movie-right-after-or-let-it-sit', 'Just finished a movie — rate it immediately or let it sit for a day?', 'Movies', 'Rate it right away', 'Let it sit', '⭐', '⏳', 47, 5, 'published'),
  ('documentary-or-drama', 'Picking something new to watch, documentary or drama?', 'Movies', 'Documentary', 'Drama', '🎥', '🎭', 38, 5, 'published'),
  ('talk-about-plot-holes-or-let-it-go', 'Movie''s over and something didn''t make sense — does the crowd pick it apart or let it go?', 'Movies', 'Pick it apart', 'Let it go', '🔍', '🤷', 51, 5, 'published'),
  ('matinee-or-evening-showing', 'Booking a ticket, matinee or evening show?', 'Movies', 'Matinee', 'Evening', '☀️', '🌙', 36, 5, 'published'),
  ('front-of-theater-or-back', 'Picking seats at the theater, front half or back half?', 'Movies', 'Front half', 'Back half', '🙋', '😎', 27, 5, 'published'),
  ('watch-with-phone-nearby-or-put-away', 'Watching a movie at home, phone within reach or put away?', 'Movies', 'Within reach', 'Put away', '📱', '📴', 63, 5, 'published'),
  ('franchise-loyalty-or-one-and-done', 'Really liked a movie — does the crowd chase the whole franchise, or leave it at one?', 'Movies', 'Chase the franchise', 'Leave it at one', '🍿', '✅', 46, 5, 'published'),
  ('movie-poster-or-trailer-decides', 'Deciding what to watch, does the poster or the trailer sell it more?', 'Movies', 'The poster', 'The trailer', '🖼️', '📽️', 30, 5, 'published'),
  ('cry-at-movies-openly-or-hide-it', 'Movie gets emotional — cry openly, or hold it in?', 'Movies', 'Cry openly', 'Hold it in', '😭', '😐', 41, 5, 'published'),
  ('remake-or-original-preferred', 'A classic gets remade — does the crowd usually prefer the original or give the remake a real shot?', 'Movies', 'Stick with the original', 'Give the remake a shot', '🕰️', '🆕', 70, 5, 'published'),
  ('character-or-plot-driven', 'What actually pulls the crowd into a story more?', 'Movies', 'Strong characters', 'A strong plot', '🎭', '🧩', 56, 5, 'published'),
  ('finish-a-bad-movie-or-quit', 'The movie''s turned out to be bad — does the crowd finish it or quit halfway?', 'Movies', 'Finish it anyway', 'Quit halfway', '🏁', '⏹️', 48, 5, 'published'),
  ('movie-night-solo-or-crowd', 'A free evening opens up — movie night alone, or with people?', 'Movies', 'Alone', 'With people', '🛋️', '👥', 45, 5, 'published'),
  ('theater-snack-candy-or-popcorn', 'At the concession stand, candy or popcorn wins?', 'Movies', 'Candy', 'Popcorn', '🍬', '🍿', 26, 5, 'published'),
  ('long-movie-or-short-movie-preferred', 'Given the choice, does the crowd prefer a long movie or a short one?', 'Movies', 'A long one', 'A short one', '⏳', '⏱️', 32, 5, 'published'),
  ('soundtrack-notice-or-not', 'Watching a movie, does the crowd actually notice the soundtrack?', 'Movies', 'Notice it', 'Barely notice', '🎵', '🙉', 39, 5, 'published'),
  ('opening-weekend-or-wait', 'New movie just released — see it opening weekend, or wait?', 'Movies', 'Opening weekend', 'Wait a while', '🎟️', '⏳', 29, 5, 'published'),
  ('movie-based-on-reviews-or-gut', 'Picking what to watch, does the crowd check reviews first or just go with a gut feeling?', 'Movies', 'Check reviews first', 'Go with gut feeling', '⭐', '💭', 58, 5, 'published'),
  ('watch-alone-first-or-wait-for-friend', 'Really want to see something — watch it solo right away, or wait to go with a friend?', 'Movies', 'Watch it solo', 'Wait for a friend', '🎬', '👯', 49, 5, 'published'),
  ('prequel-or-sequel-preferred', 'Extending a favorite story — prequel or sequel?', 'Movies', 'Prequel', 'Sequel', '⏪', '⏩', 34, 5, 'published'),
  ('movie-marathon-same-franchise-or-mix', 'Movie marathon — same franchise back to back, or a mix of different films?', 'Movies', 'Same franchise', 'A mix of films', '🎞️', '🎲', 44, 5, 'published'),
  ('discuss-during-or-after-movie', 'Something surprising just happened on screen — react out loud, or hold it until after?', 'Movies', 'React out loud', 'Hold it until after', '😲', '🤐', 53, 5, 'published'),
  ('streaming-service-loyalty-or-hop', 'Picking what to watch tonight, does the crowd stick to one streaming service or hop between a few?', 'Movies', 'Stick to one', 'Hop between a few', '📺', '🔀', 47, 5, 'published'),
  ('rewatch-with-commentary-on', 'Rewatching a favorite — does the crowd turn on the commentary track, or just watch it normally?', 'Movies', 'Turn on commentary', 'Watch normally', '🎙️', '🎬', 18, 5, 'published'),
  ('movie-food-classic-combo-or-mix', 'At the snack counter, does the crowd stick to the classic combo, or mix it up each time?', 'Movies', 'Stick to the classic', 'Mix it up', '🍿', '🎲', 60, 5, 'published'),
  ('pause-movie-for-bathroom-or-hold-it', 'Movie''s playing at home and nature calls — pause it, or hold it until a natural break?', 'Movies', 'Pause it', 'Hold it', '⏸️', '⏳', 82, 5, 'published'),
  ('movie-choice-by-vote-or-one-picks', 'Watching with a group, does the crowd vote on what to watch, or let one person just pick?', 'Movies', 'Vote on it', 'Let one person pick', '🗳️', '☝️', 55, 5, 'published'),
  ('theater-or-drive-in', 'Given the option, theater or drive-in?', 'Movies', 'Indoor theater', 'Drive-in', '🎬', '🚗', 71, 5, 'published'),
  ('warm-up-or-skip-it', 'Before exercising, does the crowd actually warm up first?', 'Sport', 'Always warm up', 'Skip straight in', '🤸', '⚡', 61, 5, 'published'),
  ('gym-or-outdoors', 'Given the choice, does the crowd work out at the gym or outdoors?', 'Sport', 'The gym', 'Outdoors', '🏋️', '🌳', 47, 5, 'published'),
  ('music-or-silence-while-training', 'Training or working out — music, or silence?', 'Sport', 'Music', 'Silence', '🎧', '🤫', 78, 5, 'published'),
  ('underdog-or-favorite-to-root-for', 'Watching a big game with no team of your own, who does the crowd root for?', 'Sport', 'The underdog', 'The favorite', '🐕', '🏆', 63, 5, 'published'),
  ('watch-live-or-highlights', 'Missed the big game — watch the full replay later, or just catch the highlights?', 'Sport', 'Watch the replay', 'Just the highlights', '📺', '📱', 42, 5, 'published'),
  ('running-outside-or-treadmill', 'Going for a run — outside, or on a treadmill?', 'Sport', 'Outside', 'Treadmill', '🏃', '🏠', 66, 5, 'published'),
  ('stretch-before-or-after', 'Stretching — before a workout, or after?', 'Sport', 'Before', 'After', '🧘', '✅', 45, 5, 'published'),
  ('play-to-win-or-just-for-fun', 'In a casual game with friends, is the crowd actually trying to win, or just there for fun?', 'Sport', 'Trying to win', 'Just there for fun', '🏆', '😄', 40, 5, 'published'),
  ('sports-jersey-wear-often-or-rarely', 'Owning a team jersey, does the crowd actually wear it often?', 'Sport', 'Wear it often', 'Rarely wear it', '👕', '📦', 34, 5, 'published'),
  ('new-sport-or-stick-with-known', 'Given a free afternoon, does the crowd try a new sport or stick with one they know?', 'Sport', 'Try something new', 'Stick with what they know', '🆕', '✅', 37, 5, 'published'),
  ('watch-sport-with-sound-or-muted', 'Watching a game at home, sound on or muted with music instead?', 'Sport', 'Sound on', 'Muted with music', '🔊', '🔇', 74, 5, 'published'),
  ('individual-record-or-team-championship', 'Which feels bigger to most people?', 'Sport', 'A personal best', 'A team championship', '🥇', '🏆', 52, 5, 'published'),
  ('exercise-alone-or-with-a-partner', 'Working out, alone or with a partner?', 'Sport', 'Alone', 'With a partner', '🧍', '🤝', 55, 5, 'published'),
  ('game-day-outfit-or-normal-clothes', 'On game day, does the crowd dress up for the team or wear normal clothes?', 'Sport', 'Dress up for the team', 'Wear normal clothes', '🎽', '👕', 30, 5, 'published'),
  ('trash-talk-friendly-games-or-quiet', 'In a friendly pickup game, does the crowd talk trash for fun, or keep it quiet?', 'Sport', 'Talk trash for fun', 'Keep it quiet', '😏', '🤐', 39, 5, 'published'),
  ('childhood-sport-or-new-hobby-now', 'As an adult, does the crowd stick with the sport they grew up playing, or try something new?', 'Sport', 'Stick with the childhood sport', 'Try something new', '🧒', '🆕', 41, 5, 'published'),
  ('watch-sport-solo-or-with-friends', 'Big game is on — watch it solo, or with friends?', 'Sport', 'Solo', 'With friends', '🛋️', '👥', 35, 5, 'published'),
  ('competitive-or-relaxed-in-casual-games', 'In a casual pickup game, is the crowd actually competitive or just relaxed about it?', 'Sport', 'Genuinely competitive', 'Pretty relaxed', '🔥', '😌', 44, 5, 'published'),
  ('skip-cooldown-or-always-do-it', 'After a workout, does the crowd actually cool down, or just stop?', 'Sport', 'Always cool down', 'Just stop', '🧊', '⏹️', 27, 5, 'published'),
  ('sports-highlights-spoiled-or-avoided', 'Big game already happened but you haven''t watched it — does the crowd avoid the score, or not bother?', 'Sport', 'Avoid the score', 'Don''t bother avoiding it', '🙈', '🤷', 58, 5, 'published'),
  ('new-gear-motivates-or-doesnt-matter', 'Buying new workout gear — does it actually motivate the crowd, or not really matter?', 'Sport', 'Genuinely motivates', 'Doesn''t really matter', '👟', '🤷', 54, 5, 'published'),
  ('race-to-finish-or-pace-yourself', 'In a casual run, does the crowd race to the finish or pace themselves?', 'Sport', 'Race to the finish', 'Pace themselves', '🏁', '⏱️', 36, 5, 'published'),
  ('sports-injury-push-through-or-rest', 'Minor ache during a workout — push through it, or stop and rest?', 'Sport', 'Push through it', 'Stop and rest', '💪', '🛑', 39, 5, 'published'),
  ('team-color-loyalty-or-just-the-sport', 'Following sports, does the crowd care more about a specific team, or just the sport itself?', 'Sport', 'A specific team', 'Just the sport', '🎽', '⚽', 61, 5, 'published'),
  ('new-years-resolution-fitness-sticks', 'A New Year''s fitness resolution — does it usually stick, or fade out?', 'Sport', 'Actually sticks', 'Fades out', '💪', '📉', 21, 5, 'published'),
  ('play-video-game-sports-or-real', 'Given a free hour, does the crowd play the real sport or the video game version?', 'Sport', 'The real sport', 'The video game', '⚽', '🎮', 44, 5, 'published'),
  ('locker-room-small-talk-or-quiet', 'In a locker room or gym changing area, does the crowd make small talk or keep to themselves?', 'Sport', 'Make small talk', 'Keep to themselves', '💬', '🤐', 32, 5, 'published'),
  ('sports-superstition-or-none', 'Before a game or big workout, does the crowd have any little superstition or ritual?', 'Sport', 'Yes, has one', 'No, none', '🍀', '🤷', 38, 5, 'published'),
  ('best-seat-close-or-wide-view', 'Picking seats at a live game — close to the action, or a wide view of the whole field?', 'Sport', 'Close to the action', 'A wide view', '🔍', '🔭', 47, 5, 'published'),
  ('play-through-bad-weather-or-reschedule', 'Weather turns bad during an outdoor game — push through, or call it off?', 'Sport', 'Push through it', 'Call it off', '🌧️', '🚫', 43, 5, 'published'),
  ('cheer-out-loud-or-quietly-invested', 'Watching a close game, does the crowd cheer out loud or stay quietly invested?', 'Sport', 'Cheer out loud', 'Quietly invested', '📣', '😶', 57, 5, 'published'),
  ('sports-drink-or-water', 'Mid-workout, what does the crowd actually reach for?', 'Sport', 'Sports drink', 'Water', '🧃', '💧', 33, 5, 'published'),
  ('try-a-team-sport-solo-practice-first', 'Joining a new team sport, does the crowd practice solo first or just show up and learn?', 'Sport', 'Practice solo first', 'Just show up', '📝', '🚶', 35, 5, 'published'),
  ('watch-replay-of-own-team-losing', 'Your team just lost — rewatch the game later, or move on?', 'Sport', 'Rewatch it', 'Move on', '🔁', '➡️', 24, 5, 'published'),
  ('celebrate-small-wins-or-only-big-ones', 'In a workout routine, does the crowd celebrate small wins, or wait for big milestones?', 'Sport', 'Celebrate small wins', 'Wait for big milestones', '🎉', '🏔️', 51, 5, 'published'),
  ('sport-for-fitness-or-for-fun', 'Why does the crowd actually play sports?', 'Sport', 'Mostly for fitness', 'Mostly for fun', '💪', '😄', 46, 5, 'published'),
  ('watch-sport-at-a-bar-or-at-home', 'Big game tonight — watch at a bar, or at home?', 'Sport', 'At a bar', 'At home', '🍻', '🏠', 38, 5, 'published'),
  ('buy-tickets-early-or-last-minute', 'Going to a live game — buy tickets early, or grab them last minute?', 'Sport', 'Buy early', 'Last minute', '🎟️', '⏰', 62, 5, 'published'),
  ('sports-commentary-love-or-mute-it', 'Watching a game, does the crowd actually enjoy the commentary, or would rather mute it?', 'Sport', 'Enjoy it', 'Would rather mute it', '🎙️', '🔇', 48, 5, 'published'),
  ('rain-check-workout-or-push-through', 'Not really feeling it before a workout — push through anyway, or skip it for today?', 'Sport', 'Push through anyway', 'Skip it for today', '💪', '😴', 44, 5, 'published'),
  ('notifications-on-or-mostly-off', 'Phone settings — notifications mostly on, or mostly muted?', 'Technology', 'Mostly on', 'Mostly muted', '🔔', '🔕', 39, 5, 'published'),
  ('read-privacy-policy-or-skip', 'New app, terms and conditions pop up — actually read it, or just accept?', 'Technology', 'Actually read it', 'Just accept', '📄', '✅', 12, 5, 'published'),
  ('laptop-or-desktop-preferred', 'Given the choice for everyday use, laptop or desktop?', 'Technology', 'Laptop', 'Desktop', '💻', '🖥️', 71, 5, 'published'),
  ('wired-or-wireless-earbuds', 'Listening on the go, wired or wireless?', 'Technology', 'Wired', 'Wireless', '🎧', '📶', 26, 5, 'published'),
  ('dark-mode-or-light-mode', 'Setting up a new app, dark mode or light mode?', 'Technology', 'Dark mode', 'Light mode', '🌙', '☀️', 68, 5, 'published'),
  ('cloud-storage-or-local-files', 'Saving important files — cloud storage, or keeping them local?', 'Technology', 'Cloud storage', 'Local files', '☁️', '💾', 64, 5, 'published'),
  ('voice-assistant-use-often-or-rarely', 'Owning a voice assistant, does the crowd actually use it often?', 'Technology', 'Use it often', 'Rarely use it', '🗣️', '📦', 31, 5, 'published'),
  ('password-manager-or-memorize', 'Managing passwords — a password manager, or just memorizing them?', 'Technology', 'Password manager', 'Memorize them', '🔐', '🧠', 44, 5, 'published'),
  ('type-with-two-thumbs-or-one-finger', 'Texting on a phone, two thumbs or one finger?', 'Technology', 'Two thumbs', 'One finger', '👍', '☝️', 73, 5, 'published'),
  ('screen-time-check-often-or-avoid', 'Screen time report on the phone — check it often, or avoid looking?', 'Technology', 'Check it often', 'Avoid looking', '📊', '🙈', 29, 5, 'published'),
  ('update-software-immediately-or-delay', 'New software update available — install right away, or put it off?', 'Technology', 'Install right away', 'Put it off', '⬇️', '⏳', 41, 5, 'published'),
  ('multiple-tabs-or-one-at-a-time', 'Browsing online, dozens of tabs open, or one at a time?', 'Technology', 'Dozens of tabs', 'One at a time', '🗂️', '1️⃣', 62, 5, 'published'),
  ('smart-home-gadgets-or-keep-it-simple', 'Setting up a home, smart gadgets everywhere, or keep it simple?', 'Technology', 'Smart gadgets everywhere', 'Keep it simple', '🏠', '🔌', 33, 5, 'published'),
  ('read-tech-reviews-before-buying-or-not', 'Buying new tech — read reviews first, or just go with a gut feeling?', 'Technology', 'Read reviews first', 'Just go with gut feeling', '⭐', '💭', 66, 5, 'published'),
  ('group-chat-muted-or-notifications-on', 'That one busy group chat — muted, or notifications on?', 'Technology', 'Muted', 'Notifications on', '🔕', '🔔', 79, 5, 'published'),
  ('physical-book-or-e-reader', 'Reading before bed, physical book or e-reader?', 'Technology', 'Physical book', 'E-reader', '📖', '📱', 58, 5, 'published'),
  ('autocorrect-trust-it-or-double-check', 'Typing on a phone — trust autocorrect, or double-check every message?', 'Technology', 'Trust autocorrect', 'Double-check everything', '⌨️', '🔍', 55, 5, 'published'),
  ('camera-photo-editing-or-raw', 'Sharing a photo, edit it first or post it as-is?', 'Technology', 'Edit it first', 'Post it as-is', '🎨', '📸', 61, 5, 'published'),
  ('tech-support-call-or-search-it-yourself', 'Something''s broken — call tech support, or search for the fix yourself?', 'Technology', 'Call for support', 'Search it yourself', '☎️', '🔍', 22, 5, 'published'),
  ('keep-old-devices-or-recycle-them', 'Old phones and gadgets pile up — keep them in a drawer, or recycle them right away?', 'Technology', 'Keep them in a drawer', 'Recycle them right away', '🗄️', '♻️', 67, 5, 'published'),
  ('video-call-camera-on-or-off', 'Joining a video call, camera on or off by default?', 'Technology', 'Camera on', 'Camera off', '🎥', '📵', 46, 5, 'published'),
  ('type-notes-or-handwrite-them', 'Taking quick notes — type them, or write by hand?', 'Technology', 'Type them', 'Write by hand', '⌨️', '✍️', 63, 5, 'published'),
  ('wifi-or-mobile-data-when-both-available', 'Both options work fine — does the crowd bother switching to WiFi, or just stay on mobile data?', 'Technology', 'Switch to WiFi', 'Stay on mobile data', '📶', '📡', 57, 5, 'published'),
  ('check-battery-percentage-often-or-ignore', 'Phone battery — check the percentage constantly, or ignore it until it dies?', 'Technology', 'Check it constantly', 'Ignore it until it dies', '🔋', '😅', 58, 5, 'published'),
  ('one-charger-everywhere-or-multiple', 'Charging cables at home — one that travels with you, or several scattered around?', 'Technology', 'One that travels with you', 'Several scattered around', '🔌', '🏠', 45, 5, 'published'),
  ('touchscreen-or-physical-buttons', 'Given the choice on a device, touchscreen or physical buttons?', 'Technology', 'Touchscreen', 'Physical buttons', '📱', '🔘', 60, 5, 'published'),
  ('keep-inbox-zero-or-let-it-pile-up', 'Email inbox — kept near zero, or letting it pile up?', 'Technology', 'Near zero', 'Let it pile up', '📭', '📬', 30, 5, 'published'),
  ('buy-latest-model-or-wait-for-deal', 'New device just launched — buy it right away, or wait for a deal?', 'Technology', 'Buy it right away', 'Wait for a deal', '🆕', '💰', 25, 5, 'published'),
  ('delete-unused-apps-or-let-them-sit', 'Phone storage''s getting full — delete unused apps first, or let them sit?', 'Technology', 'Delete unused apps first', 'Let them sit', '🗑️', '📦', 45, 5, 'published'),
  ('back-up-data-regularly-or-rarely', 'Backing up files and photos — done regularly, or rarely thought about?', 'Technology', 'Regularly', 'Rarely thought about', '💾', '🤷', 34, 5, 'published'),
  ('keep-phone-case-on-or-bare', 'Phone in hand — case on, or bare?', 'Technology', 'Case on', 'Bare', '🛡️', '📱', 84, 5, 'published'),
  ('speaker-out-loud-or-headphones-public', 'Watching something on the phone in public — speaker, or headphones?', 'Technology', 'Speaker', 'Headphones', '🔊', '🎧', 14, 5, 'published'),
  ('one-email-for-everything-or-several', 'Signing up for accounts online — one email for everything, or separate ones?', 'Technology', 'One email for everything', 'Several separate ones', '📧', '📥', 71, 5, 'published'),
  ('tech-troubleshoot-restart-first-or-dig-in', 'Something''s acting up — restart it first, or dig into the problem right away?', 'Technology', 'Restart it first', 'Dig in right away', '🔄', '🔧', 78, 5, 'published'),
  ('read-comments-on-tech-review-or-just-video', 'Watching a tech review video, does the crowd also check the comments, or just watch?', 'Technology', 'Check the comments too', 'Just watch the video', '💬', '🎥', 40, 5, 'published'),
  ('buy-extended-warranty-or-skip-it', 'New gadget at checkout — get the extended warranty, or skip it?', 'Technology', 'Get the warranty', 'Skip it', '🛡️', '🙅', 29, 5, 'published'),
  ('smartwatch-wear-daily-or-rarely', 'Owning a smartwatch, does the crowd actually wear it daily?', 'Technology', 'Wear it daily', 'Rarely wear it', '⌚', '📦', 48, 5, 'published'),
  ('auto-play-next-episode-or-turn-it-off', 'Streaming a show — leave autoplay on, or turn it off?', 'Technology', 'Leave it on', 'Turn it off', '▶️', '⏹️', 66, 5, 'published'),
  ('keep-apps-organized-in-folders-or-scattered', 'Home screen — apps organized in folders, or scattered around?', 'Technology', 'Organized in folders', 'Scattered around', '🗂️', '🎲', 51, 5, 'published'),
  ('print-documents-or-keep-digital', 'An important document — print it out, or keep it digital?', 'Technology', 'Print it out', 'Keep it digital', '🖨️', '💻', 37, 5, 'published'),
  ('raise-hand-or-stay-quiet', 'Know the answer in class — raise a hand, or stay quiet?', 'School', 'Raise a hand', 'Stay quiet', '🙋', '🤐', 46, 5, 'published'),
  ('handwritten-or-typed-notes', 'Taking notes in class — by hand, or typed?', 'School', 'By hand', 'Typed', '✍️', '⌨️', 54, 5, 'published'),
  ('homework-right-after-school-or-later', 'Homework''s assigned — start right after school, or later?', 'School', 'Right after school', 'Later', '🏃', '⏰', 37, 5, 'published'),
  ('school-lunch-or-packed-lunch', 'At lunchtime, does the crowd buy lunch or bring one from home?', 'School', 'Buy lunch', 'Bring lunch', '🍔', '🥪', 42, 5, 'published'),
  ('study-with-music-or-silence', 'Studying for a test, music or silence?', 'School', 'Music', 'Silence', '🎵', '🤫', 47, 5, 'published'),
  ('ask-teacher-or-classmate-for-help', 'Stuck on a problem — ask the teacher, or a classmate?', 'School', 'Ask the teacher', 'Ask a classmate', '🙋', '🤝', 39, 5, 'published'),
  ('all-nighter-or-full-nights-sleep', 'Big exam tomorrow — pull an all-nighter, or get a full night''s sleep?', 'School', 'Pull an all-nighter', 'Get a full night''s sleep', '🌙', '😴', 27, 5, 'published'),
  ('school-uniform-or-own-clothes-preferred', 'Given the choice, does the crowd prefer a uniform, or picking their own outfit?', 'School', 'A uniform', 'Their own outfit', '👔', '👕', 21, 5, 'published'),
  ('class-schedule-morning-classes-or-afternoon', 'Building a class schedule, morning classes or afternoon ones?', 'School', 'Morning classes', 'Afternoon classes', '🌅', '🌇', 58, 5, 'published'),
  ('group-chat-for-class-or-not', 'For a class, does the crowd join the group chat, or skip it?', 'School', 'Join it', 'Skip it', '💬', '🚫', 66, 5, 'published'),
  ('school-supplies-buy-early-or-last-minute', 'Back-to-school shopping — done early, or last minute?', 'School', 'Done early', 'Last minute', '🛍️', '⏰', 44, 5, 'published'),
  ('read-assigned-book-or-summary', 'Assigned reading for class — read the whole thing, or the summary?', 'School', 'Read the whole thing', 'Read a summary', '📖', '📝', 51, 5, 'published'),
  ('sit-with-friends-or-random-seats', 'In class, does the crowd sit with friends, or wherever''s open?', 'School', 'With friends', 'Wherever''s open', '👯', '🎲', 68, 5, 'published'),
  ('extra-credit-chase-it-or-skip-it', 'Extra credit opportunity comes up — chase it, or skip it?', 'School', 'Chase it', 'Skip it', '📈', '🙅', 55, 5, 'published'),
  ('locker-or-backpack-everything', 'Carrying school stuff — use the locker, or just carry a full backpack?', 'School', 'Use the locker', 'Carry a full backpack', '🔒', '🎒', 47, 5, 'published'),
  ('class-participation-volunteer-or-called-on', 'In class discussions, does the crowd volunteer answers, or wait to be called on?', 'School', 'Volunteer', 'Wait to be called on', '🙋', '⏳', 34, 5, 'published'),
  ('school-project-plan-first-or-dive-in', 'Starting a school project, plan it out first, or just dive in?', 'School', 'Plan it out first', 'Just dive in', '📋', '🏊', 61, 5, 'published'),
  ('field-trip-excited-or-indifferent', 'Field trip announced — genuinely excited, or pretty indifferent?', 'School', 'Genuinely excited', 'Pretty indifferent', '🎉', '😐', 63, 5, 'published'),
  ('calculator-use-or-mental-math', 'Solving a math problem, reach for a calculator, or do it mentally?', 'School', 'Reach for a calculator', 'Do it mentally', '🖩', '🧠', 58, 5, 'published'),
  ('class-clock-watch-often-or-lose-track', 'Sitting through a long class, watch the clock often, or lose track of time?', 'School', 'Watch the clock often', 'Lose track of time', '🕐', '⏳', 65, 5, 'published'),
  ('borrow-a-pen-or-always-carry-spares', 'Forgot a pen in class — borrow one, or always carry spares?', 'School', 'Borrow one', 'Always carry spares', '🙏', '🖊️', 44, 5, 'published'),
  ('school-mascot-pride-or-dont-care', 'How does the crowd actually feel about their school mascot?', 'School', 'Genuine pride', 'Don''t really care', '🦅', '🤷', 36, 5, 'published'),
  ('cram-right-before-test-or-relax', 'Minutes before a test starts, cram a bit more, or try to relax?', 'School', 'Cram a bit more', 'Try to relax', '📚', '😌', 53, 5, 'published'),
  ('class-notes-share-or-keep-private', 'Someone missed class and asks for notes — share them, or keep them private?', 'School', 'Share them', 'Keep them private', '🤝', '🔒', 82, 5, 'published'),
  ('school-dance-attend-or-skip', 'School dance is happening — attend, or skip it?', 'School', 'Attend', 'Skip it', '💃', '🚶', 47, 5, 'published'),
  ('essay-outline-first-or-just-write', 'Writing an essay — outline it first, or just start writing?', 'School', 'Outline it first', 'Just start writing', '📋', '✍️', 59, 5, 'published'),
  ('favorite-subject-strong-opinion-or-not', 'Do most people have a subject they genuinely look forward to, or is it all the same to them?', 'School', 'Genuinely look forward to one', 'It''s all the same', '❤️', '🤷', 56, 5, 'published'),
  ('exam-review-alone-or-study-group', 'Reviewing for a big exam, alone, or in a study group?', 'School', 'Alone', 'In a study group', '🧍', '👥', 49, 5, 'published'),
  ('school-assembly-pay-attention-or-tune-out', 'Sitting through a school assembly, pay attention, or tune out?', 'School', 'Pay attention', 'Tune out', '👂', '😴', 32, 5, 'published'),
  ('bring-snacks-to-class-or-not', 'During a long class, does the crowd sneak in a snack, or not bother?', 'School', 'Sneak in a snack', 'Not bother', '🍫', '🙅', 41, 5, 'published'),
  ('group-project-do-it-all-or-delegate', 'In a group project, does the crowd end up doing most of it themselves, or actually delegate?', 'School', 'End up doing most of it', 'Actually delegate', '💪', '🤝', 47, 5, 'published'),
  ('teacher-strict-or-relaxed-preferred', 'Given the choice, does the crowd prefer a strict teacher, or a relaxed one?', 'School', 'A strict teacher', 'A relaxed one', '📏', '😌', 28, 5, 'published'),
  ('school-year-count-down-days-or-not', 'As the school year winds down, does the crowd actually count the days, or not track it?', 'School', 'Count the days', 'Don''t track it', '📅', '🤷', 61, 5, 'published'),
  ('class-presentation-nervous-or-confident', 'Right before giving a class presentation, nervous, or confident?', 'School', 'Nervous', 'Confident', '😰', '😎', 68, 5, 'published'),
  ('take-elective-for-interest-or-easy-grade', 'Picking an elective, does the crowd choose something interesting, or the easiest grade?', 'School', 'Something interesting', 'The easiest grade', '🎨', '✅', 57, 5, 'published'),
  ('report-card-check-immediately-or-later', 'Report card is out — check it right away, or wait a bit?', 'School', 'Check it right away', 'Wait a bit', '👀', '⏳', 71, 5, 'published'),
  ('class-playlist-focus-music-or-none', 'Doing homework, does the crowd play a focus playlist, or work in silence?', 'School', 'Play a focus playlist', 'Work in silence', '🎧', '🤫', 52, 5, 'published'),
  ('school-supply-brand-new-or-hand-me-down', 'Starting the year, brand-new supplies, or reused from before?', 'School', 'Brand-new supplies', 'Reused from before', '🆕', '♻️', 46, 5, 'published'),
  ('sit-near-front-to-focus-or-doesnt-matter', 'Choosing a classroom seat, does sitting near the front actually help focus, or does it not matter?', 'School', 'Genuinely helps focus', 'Doesn''t really matter', '🎯', '🤷', 44, 5, 'published'),
  ('last-day-of-school-bittersweet-or-just-happy', 'Last day of school — bittersweet, or just plain happy?', 'School', 'Bittersweet', 'Just plain happy', '🥲', '🎉', 33, 5, 'published'),
  ('make-bed-every-morning-or-skip', 'First thing in the morning, make the bed, or leave it?', 'Everyday Life', 'Make the bed', 'Leave it', '🛏️', '🚪', 58, 5, 'published'),
  ('alarm-snooze-or-get-up-immediately', 'Alarm goes off — snooze it, or get up right away?', 'Everyday Life', 'Snooze it', 'Get up right away', '😴', '⏰', 71, 5, 'published'),
  ('speak-up-about-a-mistake-or-let-it-slide', 'Got the wrong order or wrong change somewhere — speak up about it, or let it slide?', 'Everyday Life', 'Speak up about it', 'Let it slide', '🗣️', '🤐', 47, 5, 'published'),
  ('umbrella-or-get-wet', 'Light rain outside — grab an umbrella, or just get a little wet?', 'Everyday Life', 'Grab an umbrella', 'Just get a little wet', '☂️', '💧', 62, 5, 'published'),
  ('small-talk-with-strangers-or-avoid-it', 'Waiting in line, does the crowd make small talk with a stranger, or avoid it?', 'Everyday Life', 'Make small talk', 'Avoid it', '💬', '🙊', 33, 5, 'published'),
  ('keys-in-same-spot-or-lose-them', 'Coming home, keys go in the same spot every time, or end up wherever?', 'Everyday Life', 'Same spot every time', 'Wherever', '🔑', '🎲', 52, 5, 'published'),
  ('grocery-shop-weekly-or-as-needed', 'Grocery shopping — one big trip a week, or as needed?', 'Everyday Life', 'One big trip a week', 'As needed', '🛒', '🔄', 55, 5, 'published'),
  ('arrive-early-or-just-in-time', 'Heading to an appointment, arrive early, or aim for just in time?', 'Everyday Life', 'Arrive early', 'Aim for just in time', '🕐', '⏱️', 49, 5, 'published'),
  ('clean-as-you-go-or-clean-later', 'Cooking a meal, clean as you go, or leave the mess for later?', 'Everyday Life', 'Clean as you go', 'Leave it for later', '🧽', '🍽️', 47, 5, 'published'),
  ('small-purchase-impulse-or-think-it-over', 'Something catches your eye at the store — buy it on impulse, or think it over first?', 'Everyday Life', 'Buy it on impulse', 'Think it over first', '⚡', '🤔', 31, 5, 'published'),
  ('answer-unknown-number-or-ignore', 'Phone rings from an unknown number — answer it, or let it go to voicemail?', 'Everyday Life', 'Answer it', 'Let it go to voicemail', '📞', '📵', 20, 5, 'published'),
  ('plan-outfit-night-before-or-morning-of', 'Picking an outfit, decide the night before, or the morning of?', 'Everyday Life', 'Night before', 'Morning of', '🌙', '☀️', 34, 5, 'published'),
  ('keep-receipts-or-toss-them', 'After a purchase, keep the receipt, or toss it?', 'Everyday Life', 'Keep it', 'Toss it', '🧾', '🗑️', 38, 5, 'published'),
  ('walk-or-drive-short-distance', 'A destination is close enough to walk — walk, or drive anyway?', 'Everyday Life', 'Walk', 'Drive anyway', '🚶', '🚗', 61, 5, 'published'),
  ('answer-door-unexpected-or-ignore', 'Unexpected knock at the door — answer it, or wait it out?', 'Everyday Life', 'Answer it', 'Wait it out', '🚪', '🙈', 44, 5, 'published'),
  ('save-good-stuff-for-special-occasion-or-use-it', 'That nice item you''re saving — use it now, or save it for a special occasion?', 'Everyday Life', 'Use it now', 'Save it for a special occasion', '🎁', '📦', 40, 5, 'published'),
  ('spontaneous-plans-or-scheduled', 'A free weekend opens up — plan it out, or stay spontaneous?', 'Everyday Life', 'Plan it out', 'Stay spontaneous', '📅', '🎲', 43, 5, 'published'),
  ('finish-book-you-dislike-or-quit', 'A book turns out disappointing halfway through — finish it anyway, or put it down?', 'Everyday Life', 'Finish it anyway', 'Put it down', '🏁', '⏹️', 39, 5, 'published'),
  ('keep-junk-drawer-or-organize-everything', 'That one drawer of miscellaneous stuff — everyone has one, or everything has a place?', 'Everyday Life', 'There''s a junk drawer', 'Everything has a place', '🗄️', '📐', 66, 5, 'published'),
  ('small-argument-let-it-go-or-address-it', 'A small disagreement with someone — let it go, or bring it up?', 'Everyday Life', 'Let it go', 'Bring it up', '🤐', '💬', 57, 5, 'published'),
  ('new-years-resolutions-make-them-or-skip', 'New Year — actually set resolutions, or skip that entirely?', 'Everyday Life', 'Set resolutions', 'Skip it entirely', '🎆', '🤷', 48, 5, 'published'),
  ('save-or-spend-unexpected-money', 'Unexpected extra money shows up — save it, or spend it?', 'Everyday Life', 'Save it', 'Spend it', '🏦', '🛍️', 65, 5, 'published'),
  ('read-instructions-for-furniture-or-wing-it', 'New furniture to assemble — read the instructions, or wing it?', 'Everyday Life', 'Read the instructions', 'Wing it', '📘', '🔧', 41, 5, 'published'),
  ('plan-vacation-in-detail-or-play-it-by-ear', 'On vacation, plan every detail, or play it by ear?', 'Everyday Life', 'Plan every detail', 'Play it by ear', '📋', '🎲', 45, 5, 'published'),
  ('answer-emails-immediately-or-batch-them', 'New email arrives — answer it right away, or batch them for later?', 'Everyday Life', 'Answer right away', 'Batch them for later', '📧', '📥', 39, 5, 'published'),
  ('cross-when-clear-or-wait-for-signal', 'No cars in sight — cross right away, or wait for the signal?', 'Everyday Life', 'Cross right away', 'Wait for the signal', '🚶', '🚦', 44, 5, 'published'),
  ('keep-old-clothes-or-donate-them', 'Clothes you haven''t worn in years — keep them just in case, or donate them?', 'Everyday Life', 'Keep them just in case', 'Donate them', '👕', '🎁', 47, 5, 'published'),
  ('plan-b-always-or-figure-it-out', 'Making plans, always have a backup, or figure it out if needed?', 'Everyday Life', 'Always have a backup', 'Figure it out if needed', '🅱️', '🤷', 42, 5, 'published'),
  ('text-back-immediately-or-when-convenient', 'A message comes in — reply right away, or when it''s convenient?', 'Everyday Life', 'Reply right away', 'When it''s convenient', '⚡', '⏳', 46, 5, 'published'),
  ('real-email-or-separate-one-for-signups', 'Signing up for something new online, real email, or a separate one just for that?', 'Everyday Life', 'Real email', 'A separate one', '📧', '🗑️', 58, 5, 'published'),
  ('hang-clothes-or-fold-them', 'Putting laundry away, hang it up, or fold it?', 'Everyday Life', 'Hang it up', 'Fold it', '👔', '📚', 51, 5, 'published'),
  ('bring-a-gift-when-visiting-or-not', 'Visiting someone''s home, bring a small gift, or not necessary?', 'Everyday Life', 'Bring a small gift', 'Not necessary', '🎁', '🤷', 63, 5, 'published'),
  ('remember-names-easily-or-struggle', 'Just met someone new — remember their name easily, or forget it almost instantly?', 'Everyday Life', 'Remember it easily', 'Forget it almost instantly', '🧠', '😅', 36, 5, 'published'),
  ('keep-tv-on-for-background-noise-or-off', 'At home alone, keep the TV on for background noise, or off in silence?', 'Everyday Life', 'On for background noise', 'Off in silence', '📺', '🤫', 47, 5, 'published'),
  ('write-a-to-do-list-or-keep-it-in-your-head', 'Managing tasks for the day, write a to-do list, or keep it all in your head?', 'Everyday Life', 'Write a list', 'Keep it in your head', '📝', '🧠', 60, 5, 'published'),
  ('keep-appointments-in-app-or-memory', 'Remembering appointments, calendar app, or just memory?', 'Everyday Life', 'Calendar app', 'Just memory', '📅', '🧠', 68, 5, 'published'),
  ('return-shopping-cart-or-leave-it', 'Finished loading the car at the store — return the cart, or leave it in the lot?', 'Everyday Life', 'Return the cart', 'Leave it in the lot', '🛒', '🅿️', 78, 5, 'published'),
  ('answer-how-are-you-honestly-or-fine', 'Someone asks ''how are you?'' in passing — answer honestly, or just say ''fine''?', 'Everyday Life', 'Answer honestly', 'Just say fine', '💬', '🙂', 24, 5, 'published'),
  ('keep-spare-change-or-cards-only', 'Paying for small things, cash and change, or cards only?', 'Everyday Life', 'Cash and change', 'Cards only', '💵', '💳', 22, 5, 'published'),
  ('plan-errands-in-one-trip-or-spread-out', 'Running errands — one big trip, or spread across the week?', 'Everyday Life', 'One big trip', 'Spread across the week', '🚗', '📆', 57, 5, 'published'),
  ('superpower-flight-or-invisibility', 'Given a superpower, flight or invisibility?', 'Random', 'Flight', 'Invisibility', '🦸', '🫥', 63, 5, 'published'),
  ('mountains-or-forest-hike', 'Picking a hike, mountains or forest?', 'Random', 'Mountains', 'Forest', '⛰️', '🌲', 51, 5, 'published'),
  ('rain-or-snow-preferred', 'Given the choice, does the crowd prefer rain or snow?', 'Random', 'Rain', 'Snow', '🌧️', '❄️', 46, 5, 'published'),
  ('live-in-the-past-or-future', 'If you had to time travel and stay, past or future?', 'Random', 'The past', 'The future', '🕰️', '🚀', 41, 5, 'published'),
  ('read-fiction-or-nonfiction', 'Picking up a book, fiction or nonfiction?', 'Random', 'Fiction', 'Nonfiction', '📚', '📰', 68, 5, 'published'),
  ('birthday-party-or-quiet-day', 'For their own birthday, does the crowd want a party, or a quiet day?', 'Random', 'A party', 'A quiet day', '🎉', '🕯️', 44, 5, 'published'),
  ('city-or-countryside-living', 'Given the choice, city or countryside?', 'Random', 'The city', 'The countryside', '🏙️', '🌾', 47, 5, 'published'),
  ('famous-or-anonymous', 'Given the choice, would most people rather be famous, or live anonymously?', 'Random', 'Famous', 'Anonymous', '🌟', '🫥', 32, 5, 'published'),
  ('neat-freak-or-organized-chaos', 'Describing their own space, neat freak, or organized chaos?', 'Random', 'Neat freak', 'Organized chaos', '🧹', '🌪️', 45, 5, 'published'),
  ('lottery-tell-everyone-or-keep-quiet', 'Just won the lottery — tell everyone, or keep it quiet?', 'Random', 'Tell everyone', 'Keep it quiet', '📣', '🤫', 28, 5, 'published'),
  ('summer-or-winter-preferred', 'Given the choice, summer or winter?', 'Random', 'Summer', 'Winter', '☀️', '❄️', 61, 5, 'published'),
  ('boat-or-cabin', 'Given the choice of one, a boat, or a cabin in the woods?', 'Random', 'A boat', 'A cabin in the woods', '⛵', '🏕️', 47, 5, 'published'),
  ('read-horoscope-or-ignore-it', 'Horoscope pops up somewhere — read it, or scroll past?', 'Random', 'Read it', 'Scroll past', '🔮', '⏭️', 34, 5, 'published'),
  ('plan-a-party-or-just-show-up', 'For a group event, does the crowd like planning it, or just showing up?', 'Random', 'Plan it', 'Just show up', '📋', '🚶', 42, 5, 'published'),
  ('name-a-pet-quickly-or-agonize', 'Getting a new pet, does the crowd name it quickly, or agonize over the perfect name?', 'Random', 'Name it quickly', 'Agonize over it', '⚡', '🤔', 49, 5, 'published'),
  ('dream-job-money-or-passion', 'Choosing a career, does the crowd prioritize money, or passion?', 'Random', 'The money', 'The passion', '💰', '❤️', 39, 5, 'published'),
  ('classic-car-or-a-new-one', 'Given the choice, an old classic car, or a brand-new one?', 'Random', 'A classic car', 'A brand-new one', '🚗', '🆕', 44, 5, 'published'),
  ('explore-a-new-city-alone-or-guided', 'Visiting a new city, explore it alone, or take a guided tour?', 'Random', 'Explore it alone', 'Take a guided tour', '🧭', '🚌', 66, 5, 'published'),
  ('quiet-night-in-or-night-out', 'A free Friday night — quiet night in, or night out?', 'Random', 'Quiet night in', 'Night out', '🛋️', '🎉', 58, 5, 'published'),
  ('keep-a-journal-or-dont', 'Does the crowd actually keep a journal, or never bother?', 'Random', 'Keep a journal', 'Never bother', '📓', '🤷', 26, 5, 'published'),
  ('adventurous-or-cautious-by-nature', 'By nature, is the crowd more adventurous, or more cautious?', 'Random', 'Adventurous', 'Cautious', '🧗', '🛡️', 44, 5, 'published'),
  ('own-a-garden-or-not-interested', 'Given the space, would the crowd actually keep a garden, or not be interested?', 'Random', 'Keep a garden', 'Not interested', '🌱', '🤷', 51, 5, 'published'),
  ('name-a-star-or-plant-a-tree', 'A meaningful gesture — naming a star after someone, or planting a tree?', 'Random', 'Naming a star', 'Planting a tree', '⭐', '🌳', 47, 5, 'published'),
  ('hammock-or-porch-swing', 'Given the choice for the backyard, a hammock, or a porch swing?', 'Random', 'A hammock', 'A porch swing', '🛌', '🪑', 58, 5, 'published'),
  ('convertible-or-never-interested', 'Given the option, would the crowd drive a convertible, or never be interested?', 'Random', 'Drive a convertible', 'Never interested', '🚗', '🚫', 41, 5, 'published'),
  ('handwritten-letter-or-a-call', 'Reconnecting with an old friend — a handwritten letter, or a call?', 'Random', 'A handwritten letter', 'A call', '✉️', '📞', 24, 5, 'published'),
  ('live-without-music-or-without-movies', 'Forced to give up one forever, music or movies?', 'Random', 'Music', 'Movies', '🎵', '🎬', 61, 5, 'published'),
  ('collect-something-or-not-a-collector', 'Does the crowd actually collect anything, or not really a collector?', 'Random', 'Collects something', 'Not really a collector', '🗃️', '🤷', 43, 5, 'published'),
  ('hot-tub-or-home-theater', 'Given the choice for the backyard or basement, a hot tub, or a home theater?', 'Random', 'A hot tub', 'A home theater', '🛁', '🎬', 46, 5, 'published'),
  ('accept-price-or-negotiate', 'Buying something big — accept the listed price, or try to negotiate?', 'Random', 'Accept the listed price', 'Try to negotiate', '🏷️', '🤝', 38, 5, 'published'),
  ('island-or-mansion', 'Given the choice, a private island, or a mansion?', 'Random', 'A private island', 'A mansion', '🏝️', '🏰', 57, 5, 'published'),
  ('road-trip-planned-or-spontaneous', 'A road trip''s happening — planned out, or completely spontaneous?', 'Random', 'Planned out', 'Completely spontaneous', '🗺️', '🎲', 39, 5, 'published'),
  ('keep-a-souvenir-or-just-photos', 'On a trip somewhere memorable, buy a souvenir, or just take photos?', 'Random', 'Buy a souvenir', 'Just take photos', '🎁', '📸', 40, 5, 'published'),
  ('talk-to-yourself-out-loud-or-in-head', 'Working through a problem alone, talk it out loud, or just in your head?', 'Random', 'Talk it out loud', 'Just in your head', '🗣️', '🧠', 33, 5, 'published'),
  ('pool-or-a-big-backyard', 'Given the choice, a pool, or a big backyard?', 'Random', 'A pool', 'A big backyard', '🏊', '🌳', 48, 5, 'published'),
  ('celebrity-meet-excited-or-not', 'Chance to meet a celebrity — genuinely excited, or wouldn''t really care?', 'Random', 'Genuinely excited', 'Wouldn''t really care', '🤩', '🤷', 46, 5, 'published'),
  ('vintage-item-or-brand-new', 'Given the choice, a vintage find, or something brand new?', 'Random', 'A vintage find', 'Something brand new', '🕰️', '🆕', 41, 5, 'published'),
  ('offline-day-could-or-couldnt', 'A full day completely offline — could actually do it, or couldn''t manage?', 'Random', 'Could actually do it', 'Couldn''t manage', '🏕️', '📵', 39, 5, 'published'),
  ('loud-car-or-quiet-one', 'Given the choice, a car that turns heads, or one that just blends in?', 'Random', 'Turns heads', 'Blends in', '🚗', '🙈', 33, 5, 'published'),
  ('favorite-season-instant-or-torn', 'Asked their favorite season, does the crowd answer instantly, or feel torn?', 'Random', 'Answer instantly', 'Feel torn', '⚡', '🤔', 54, 5, 'published'),
  ('treehouse-want-or-not', 'As a kid or even now, does the crowd actually want a treehouse, or never really cared?', 'Random', 'Actually want one', 'Never really cared', '🌳', '🤷', 42, 5, 'published'),
  ('like-posts-often-or-rarely', 'Scrolling through a feed, does the crowd like posts often, or rarely bother?', 'Internet Culture', 'Like them often', 'Rarely bother', '❤️', '🙈', 47, 5, 'published'),
  ('text-in-full-sentences-or-fragments', 'Texting a friend, full sentences, or short fragments?', 'Internet Culture', 'Full sentences', 'Short fragments', '📝', '💬', 44, 5, 'published'),
  ('video-call-or-text-with-friends', 'Catching up with a friend online, video call, or just text?', 'Internet Culture', 'Video call', 'Just text', '📹', '💬', 33, 5, 'published'),
  ('use-gifs-in-chats-or-never', 'Replying in a chat, does the crowd use gifs, or never bother?', 'Internet Culture', 'Use gifs', 'Never bother', '🎞️', '🙅', 46, 5, 'published'),
  ('public-or-private-social-account', 'Social media account — public, or private?', 'Internet Culture', 'Public', 'Private', '🌐', '🔒', 54, 5, 'published'),
  ('save-memes-or-just-scroll-past', 'See a funny meme — save it for later, or just scroll past?', 'Internet Culture', 'Save it for later', 'Scroll past', '💾', '⏭️', 41, 5, 'published'),
  ('reply-to-every-comment-or-just-a-few', 'Posted something that got a lot of comments — reply to all of them, or just a few?', 'Internet Culture', 'Reply to all of them', 'Just a few', '💬', '🤏', 26, 5, 'published'),
  ('livestream-watch-or-catch-clip-later', 'A livestream''s happening — watch it live, or catch a clip later?', 'Internet Culture', 'Watch it live', 'Catch a clip later', '🔴', '⏭️', 31, 5, 'published'),
  ('online-username-real-name-or-alias', 'Signing up somewhere online, real name, or a made-up alias?', 'Internet Culture', 'Real name', 'A made-up alias', '🪪', '🎭', 46, 5, 'published'),
  ('share-location-with-friends-or-not', 'Location sharing with friends — turned on, or off?', 'Internet Culture', 'Turned on', 'Off', '📍', '🚫', 39, 5, 'published'),
  ('use-caps-lock-for-emphasis-or-never', 'Texting something important, use caps lock for emphasis, or never?', 'Internet Culture', 'Use caps lock', 'Never', '🔠', '🚫', 32, 5, 'published'),
  ('delete-old-posts-or-leave-them-up', 'Old posts from years ago — delete them, or leave them up?', 'Internet Culture', 'Delete them', 'Leave them up', '🗑️', '📌', 44, 5, 'published'),
  ('short-clips-or-one-long-video', 'Free time on the phone, scroll short clips, or watch one long video?', 'Internet Culture', 'Scroll short clips', 'Watch one long video', '📱', '🎬', 68, 5, 'published'),
  ('follow-back-everyone-or-selective', 'Someone follows you online — follow back automatically, or be selective?', 'Internet Culture', 'Follow back automatically', 'Be selective', '🔄', '🎯', 37, 5, 'published'),
  ('post-daily-or-rarely-post', 'How often does the crowd actually post anything online?', 'Internet Culture', 'Pretty often', 'Rarely at all', '📸', '🤐', 33, 5, 'published'),
  ('text-typos-fix-them-or-leave-them', 'Typo in a text you already sent — send a correction, or leave it?', 'Internet Culture', 'Send a correction', 'Leave it', '✏️', '🤷', 46, 5, 'published'),
  ('use-read-receipts-or-turn-them-off', 'Messaging apps — leave read receipts on, or turn them off?', 'Internet Culture', 'Leave them on', 'Turn them off', '👀', '🚫', 41, 5, 'published'),
  ('online-cart-buy-now-or-let-it-sit', 'Something''s in the online cart — buy it right away, or let it sit?', 'Internet Culture', 'Buy it right away', 'Let it sit', '🛒', '⏳', 36, 5, 'published'),
  ('voice-message-or-typed-message', 'Sending a quick message, voice memo, or typed?', 'Internet Culture', 'Voice memo', 'Typed', '🎙️', '⌨️', 22, 5, 'published'),
  ('screenshot-and-share-or-just-tell-them', 'Something funny in a chat — screenshot and share it, or just describe it later?', 'Internet Culture', 'Screenshot and share it', 'Just describe it later', '📸', '🗣️', 63, 5, 'published'),
  ('news-from-social-media-or-other-sources', 'Hearing about something happening, social media first, or another source?', 'Internet Culture', 'Social media first', 'Another source', '📱', '📰', 61, 5, 'published'),
  ('group-chat-lurk-or-participate', 'In a busy group chat, does the crowd mostly participate, or mostly lurk?', 'Internet Culture', 'Mostly participate', 'Mostly lurk', '🗣️', '👀', 34, 5, 'published'),
  ('online-review-leave-one-or-never', 'After buying something online, leave a review, or never bother?', 'Internet Culture', 'Leave a review', 'Never bother', '⭐', '🤷', 26, 5, 'published'),
  ('video-thumbnail-or-title-decides-click', 'Deciding whether to click a video, thumbnail, or title?', 'Internet Culture', 'The thumbnail', 'The title', '🖼️', '📝', 57, 5, 'published'),
  ('notification-badge-zero-or-ignore', 'Unread notification badges — keep them at zero, or let them pile up?', 'Internet Culture', 'Keep them at zero', 'Let them pile up', '0️⃣', '🔴', 47, 5, 'published'),
  ('share-a-post-or-just-enjoy-it', 'See something great online — share it, or just enjoy it privately?', 'Internet Culture', 'Share it', 'Enjoy it privately', '🔁', '🤫', 39, 5, 'published'),
  ('online-argument-jump-in-or-scroll-past', 'Comments section turns into an argument — jump in, or scroll past?', 'Internet Culture', 'Jump in', 'Scroll past', '🥊', '⏭️', 14, 5, 'published'),
  ('profile-picture-change-often-or-rarely', 'Profile picture — changed often, or basically never?', 'Internet Culture', 'Changed often', 'Basically never', '🔄', '🖼️', 24, 5, 'published'),
  ('text-someone-happy-birthday-or-call', 'Someone''s birthday — send a text, or actually call?', 'Internet Culture', 'Send a text', 'Actually call', '💬', '📞', 71, 5, 'published'),
  ('online-quiz-take-it-or-scroll-past', 'A fun online quiz pops up — take it, or scroll past?', 'Internet Culture', 'Take it', 'Scroll past', '🧩', '⏭️', 36, 5, 'published'),
  ('keep-old-chats-or-clear-them-out', 'Old conversations piling up — keep them, or clear them out?', 'Internet Culture', 'Keep them', 'Clear them out', '📥', '🗑️', 68, 5, 'published'),
  ('reply-with-a-meme-or-with-words', 'Responding to a funny message, a meme, or actual words?', 'Internet Culture', 'A meme', 'Actual words', '🖼️', '💬', 46, 5, 'published'),
  ('finish-videos-or-bail-early', 'Watching a video online, does the crowd usually stick around to the end, or bail out partway through?', 'Internet Culture', 'Stick around to the end', 'Bail out partway through', '▶️', '🚪', 33, 5, 'published'),
  ('share-screen-time-or-keep-private', 'Weekly screen time report — share it with friends for laughs, or keep it private?', 'Internet Culture', 'Share it for laughs', 'Keep it private', '😂', '🔒', 22, 5, 'published'),
  ('online-persona-matches-or-different', 'Does the crowd feel their online persona matches who they are in person, or is it pretty different?', 'Internet Culture', 'Pretty much matches', 'Pretty different', '🪞', '🎭', 58, 5, 'published'),
  ('text-one-word-or-elaborate', 'Replying to a casual text, one word, or a full elaborate answer?', 'Internet Culture', 'One word', 'A full elaborate answer', '1️⃣', '📜', 42, 5, 'published'),
  ('mute-a-friend-online-or-never', 'A friend posts a lot online — mute them quietly, or never would?', 'Internet Culture', 'Mute them quietly', 'Never would', '🔇', '🤷', 31, 5, 'published'),
  ('join-online-trend-or-skip-it', 'A new online trend or challenge shows up — join in, or skip it?', 'Internet Culture', 'Join in', 'Skip it', '🌊', '🙅', 33, 5, 'published'),
  ('phone-face-down-or-up-in-company', 'Phone on the table with company around — face down, or face up?', 'Internet Culture', 'Face down', 'Face up', '📴', '📱', 62, 5, 'published'),
  ('check-phone-first-thing-or-later', 'First thing after waking up, check the phone right away, or wait a bit?', 'Internet Culture', 'Check it right away', 'Wait a bit', '📱', '⏳', 64, 5, 'published'),
  ('online-debate-change-mind-or-dig-in', 'In an online discussion, does the crowd ever actually change their mind, or dig in further?', 'Internet Culture', 'Sometimes change their mind', 'Usually dig in further', '🔄', '⛏️', 46, 5, 'published')
on conflict (id) do nothing;
