import { Question } from "@/lib/types";

/**
 * Demo/seed questions. `seededResultPercentageA` stands in for a real crowd
 * result until enough live votes exist (see `minimumVotes`), at which point
 * the live tally takes over — see getQuestionResult() in store/index.ts.
 */
const seed: Omit<Question, "status" | "createdAt">[] = [
  // Food
  {
    id: "sweet-or-savory-breakfast",
    category: "Food",
    text: "Which would most people choose for breakfast?",
    optionA: "Sweet",
    optionB: "Savory",
    emojiA: "🍩",
    emojiB: "🥓",
    seededResultPercentageA: 47,
    minimumVotes: 5,
  },
  {
    id: "pizza-or-burger-movie-night",
    category: "Food",
    text: "Which would most people choose for a movie night?",
    optionA: "Pizza",
    optionB: "Burger",
    emojiA: "🍕",
    emojiB: "🍔",
    seededResultPercentageA: 62,
    minimumVotes: 5,
  },
  {
    id: "pineapple-on-pizza",
    category: "Food",
    text: "Pineapple on pizza — yes or no?",
    optionA: "Yes",
    optionB: "No",
    emojiA: "🍍",
    emojiB: "🚫",
    seededResultPercentageA: 33,
    minimumVotes: 5,
  },
  {
    id: "cereal-or-milk-first",
    category: "Food",
    text: "Which goes into the bowl first?",
    optionA: "Cereal",
    optionB: "Milk",
    emojiA: "🥣",
    emojiB: "🥛",
    seededResultPercentageA: 71,
    minimumVotes: 5,
  },
  // Movies
  {
    id: "rewatch-or-new-movie",
    category: "Movies",
    text: "Which would most people choose tonight?",
    optionA: "Rewatch a favorite",
    optionB: "Try something new",
    emojiA: "🔁",
    emojiB: "🎬",
    seededResultPercentageA: 58,
    minimumVotes: 5,
  },
  {
    id: "sweet-or-salty-popcorn",
    category: "Movies",
    text: "Which popcorn wins at the cinema?",
    optionA: "Sweet",
    optionB: "Salty",
    emojiA: "🍿",
    emojiB: "🧂",
    seededResultPercentageA: 41,
    minimumVotes: 5,
  },
  {
    id: "subtitles-on-or-off",
    category: "Movies",
    text: "Subtitles on, even in your own language?",
    optionA: "On",
    optionB: "Off",
    emojiA: "📝",
    emojiB: "🙈",
    seededResultPercentageA: 45,
    minimumVotes: 5,
  },
  {
    id: "cinema-or-couch",
    category: "Movies",
    text: "Which would most people choose to watch a new release?",
    optionA: "Cinema",
    optionB: "Couch at home",
    emojiA: "🎥",
    emojiB: "🛋️",
    seededResultPercentageA: 39,
    minimumVotes: 5,
  },
  // Sport
  {
    id: "play-or-watch-sport",
    category: "Sport",
    text: "Which would most people choose?",
    optionA: "Play the sport",
    optionB: "Watch the sport",
    emojiA: "⚽",
    emojiB: "📺",
    seededResultPercentageA: 54,
    minimumVotes: 5,
  },
  {
    id: "morning-or-evening-workout",
    category: "Sport",
    text: "When do most people prefer to work out?",
    optionA: "Morning",
    optionB: "Evening",
    emojiA: "🌅",
    emojiB: "🌙",
    seededResultPercentageA: 48,
    minimumVotes: 5,
  },
  {
    id: "team-or-solo-sport",
    category: "Sport",
    text: "Which would most people choose to play?",
    optionA: "Team sport",
    optionB: "Solo sport",
    emojiA: "🤝",
    emojiB: "🏃",
    seededResultPercentageA: 61,
    minimumVotes: 5,
  },
  {
    id: "win-ugly-or-lose-beautifully",
    category: "Sport",
    text: "Which would most people rather do?",
    optionA: "Win ugly",
    optionB: "Lose playing beautifully",
    emojiA: "🏆",
    emojiB: "🎨",
    seededResultPercentageA: 67,
    minimumVotes: 5,
  },
  // Technology
  {
    id: "iphone-or-android",
    category: "Technology",
    text: "Which would most people choose?",
    optionA: "iPhone",
    optionB: "Android",
    emojiA: "📱",
    emojiB: "🤖",
    seededResultPercentageA: 55,
    minimumVotes: 5,
  },
  {
    id: "instructions-or-figure-it-out",
    category: "Technology",
    text: "New gadget just arrived. What now?",
    optionA: "Figure it out yourself",
    optionB: "Read the instructions",
    emojiA: "🧩",
    emojiB: "📖",
    seededResultPercentageA: 73,
    minimumVotes: 5,
  },
  {
    id: "keyboard-or-phone-typing",
    category: "Technology",
    text: "Which would most people choose to type a long message?",
    optionA: "Real keyboard",
    optionB: "Phone",
    emojiA: "⌨️",
    emojiB: "📱",
    seededResultPercentageA: 64,
    minimumVotes: 5,
  },
  {
    id: "keep-phone-or-upgrade-yearly",
    category: "Technology",
    text: "Which would most people choose?",
    optionA: "Keep it till it breaks",
    optionB: "New phone every year",
    emojiA: "🔧",
    emojiB: "🆕",
    seededResultPercentageA: 78,
    minimumVotes: 5,
  },
  // School
  {
    id: "study-night-before-or-spread-out",
    category: "School",
    text: "How does most people study for a big test?",
    optionA: "Night before",
    optionB: "Spread it out",
    emojiA: "🌙",
    emojiB: "📅",
    seededResultPercentageA: 52,
    minimumVotes: 5,
  },
  {
    id: "solo-or-group-project",
    category: "School",
    text: "Given the choice, which would most people pick?",
    optionA: "Solo project",
    optionB: "Group project",
    emojiA: "🙋",
    emojiB: "👥",
    seededResultPercentageA: 60,
    minimumVotes: 5,
  },
  {
    id: "front-row-or-back-row",
    category: "School",
    text: "Which seat do most people choose in class?",
    optionA: "Back row",
    optionB: "Front row",
    emojiA: "😎",
    emojiB: "🙋‍♂️",
    seededResultPercentageA: 69,
    minimumVotes: 5,
  },
  {
    id: "summer-or-winter-break",
    category: "School",
    text: "Which break do most people look forward to more?",
    optionA: "Summer break",
    optionB: "Winter break",
    emojiA: "🌞",
    emojiB: "❄️",
    seededResultPercentageA: 74,
    minimumVotes: 5,
  },
  // Everyday Life
  {
    id: "morning-or-evening-shower",
    category: "Everyday Life",
    text: "Which would most people choose?",
    optionA: "Morning shower",
    optionB: "Evening shower",
    emojiA: "🚿",
    emojiB: "🌙",
    seededResultPercentageA: 56,
    minimumVotes: 5,
  },
  {
    id: "window-or-aisle-seat",
    category: "Everyday Life",
    text: "On a long trip, which seat do most people pick?",
    optionA: "Window",
    optionB: "Aisle",
    emojiA: "🪟",
    emojiB: "🚶",
    seededResultPercentageA: 63,
    minimumVotes: 5,
  },
  {
    id: "text-or-call",
    category: "Everyday Life",
    text: "Which would most people choose to reach a friend?",
    optionA: "Text",
    optionB: "Call",
    emojiA: "💬",
    emojiB: "📞",
    seededResultPercentageA: 81,
    minimumVotes: 5,
  },
  {
    id: "early-bird-or-night-owl",
    category: "Everyday Life",
    text: "Which are most people?",
    optionA: "Night owl",
    optionB: "Early bird",
    emojiA: "🦉",
    emojiB: "🐦",
    seededResultPercentageA: 57,
    minimumVotes: 5,
  },
  // Random
  {
    id: "cats-or-dogs",
    category: "Random",
    text: "Which would most people choose?",
    optionA: "Dogs",
    optionB: "Cats",
    emojiA: "🐶",
    emojiB: "🐱",
    seededResultPercentageA: 59,
    minimumVotes: 5,
  },
  {
    id: "beach-or-mountain-vacation",
    category: "Random",
    text: "Which vacation would most people choose?",
    optionA: "Beach",
    optionB: "Mountains",
    emojiA: "🏖️",
    emojiB: "⛰️",
    seededResultPercentageA: 55,
    minimumVotes: 5,
  },
  {
    id: "more-time-or-more-money",
    category: "Random",
    text: "Which would most people choose, if they had to pick?",
    optionA: "More time",
    optionB: "More money",
    emojiA: "⏳",
    emojiB: "💰",
    seededResultPercentageA: 66,
    minimumVotes: 5,
  },
  // Internet Culture
  {
    id: "lots-of-emojis-or-none",
    category: "Internet Culture",
    text: "Which describes how most people text?",
    optionA: "Lots of emojis",
    optionB: "No emojis at all",
    emojiA: "😂",
    emojiB: "🔠",
    seededResultPercentageA: 53,
    minimumVotes: 5,
  },
  {
    id: "read-or-skip-comments",
    category: "Internet Culture",
    text: "Which would most people choose on a video?",
    optionA: "Skip the comments",
    optionB: "Read the comments",
    emojiA: "🙈",
    emojiB: "💬",
    seededResultPercentageA: 62,
    minimumVotes: 5,
  },
  {
    id: "post-the-moment-or-watch",
    category: "Internet Culture",
    text: "At a big moment, what do most people do first?",
    optionA: "Just watch it happen",
    optionB: "Post it",
    emojiA: "👀",
    emojiB: "📸",
    seededResultPercentageA: 71,
    minimumVotes: 5,
  },
];

export const seedQuestions: Question[] = seed.map((q) => ({
  ...q,
  status: "published",
  createdAt: "2026-01-01T00:00:00.000Z",
}));
